### PR TITLE
Fix i18n implementation

### LINKED ISSUE #8: Get locale code from string.xml instead of Locale
There is some problems in the current i18n implementation.

Let me explain it:

### Background
There is lots of regions in the Chinese language zone, such as CN, HK, TW, MO and SG.

But there are only two main language variants: the Simplified Chinese(简体中文) and the Traditional Chinese(繁體中文).

The CN and SG use Simplified Chinese, and the rest of the regions use Traditional Chinese.

We should use Traditional Chinese as the **fallback**, because it covers more regions.

As above, we came across the project struct, as I mentioned at https://github.com/antest1/kcanotify/issues/6#issuecomment-286493663:

```
value-zh => Traditional Chinese
value-zh-rCN => Simplified Chinese
value-zh-rSG => Simplified Chinese
``` 

### Problem

There comes the problem, we only have two language variants, and need to deal with a lot of regions.

Now the project using the following [code](https://github.com/antest1/kcanotify/blob/c3028727109c90233f396a87919c739196958eff/app/src/main/java/com/antest1/kcanotify/MainActivity.java#L297) to retrieve the localecode:

```java
String language = Locale.getDefault().getLanguage();
String country = Locale.getDefault().getCountry();
```

And the `languageOptionValue` only provide two `zh` value: `zh-CN` and `zh-TW`

What if a user in HK, and the default locale is `zh-HK`, as the structure above, it will fallback to `value-zh` which provides the Traditional Chinese.

But, there is no `zh-HK` in `languageOptionValue`, then the entry of Language Setting will display the **English**.

And when the user restart the app, it will set the Configuration Locale to English even if we have the correct Localized Resource.

### Solution

As [This StackOverflow](http://stackoverflow.com/questions/8690460/how-to-get-language-locale-currently-android-app-displays) describe, we should set the correct `localecode` in each `strings.xml`.

And retrieve the `localecode` in `strings.xml` which is the **real** currently using language variant.

### PR DESCRIPTION
**Pull request by wafer-li**
Fix #8 

You could see the test at https://github.com/wafer-li/kcanotify/tree/test-chinese-fallback

Or you could test it by youself

### CODE REVIEW

**Comment by wafer-li** [comment]
There might be the little problem:

Now, the `value-en` is redundant.

The default `value/string.xml` will do the job.

It will be better to unify the two resources.

**Comment by antest1** [comment]
okay, I'll remove the value-en resource.

**Comment by wafer-li** [comment]
Actually, there are some differences between these two resources.

That is why I didn't remove the `value-en`

image

**Comment by antest1** [comment]
That part is just I didn't fixed before, so it would be no problem.

**Comment by wafer-li** [comment]
OK,  I am looking forward to see the new release

**Pull request merged**
